server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mail80782258@gmail.com
    password: dlyrklicfisroohv
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com