server:
  port: 7777

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail80782258@gmail.com
    password: dlyrklicfisroohv
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com